# Strings
string = 'Welcome to my World!'
print("Prints complete string - print(string)")
print(string)
print("--------------------------------------------")
print("Prints first character of the string - print(string[0])")           
print (string[0])
print("--------------------------------------------")
print("Prints characters starting from 3rd to 11th - print(string[2:10])")        
print (string[2:10])
print("--------------------------------------------")
print("Prints string starting from 9rd character - print(string[8:])")
print(string[8:])
print("--------------------------------------------")
print("# Prints string two times - print(string * 2)")
print(string * 2)
print("--------------------------------------------")
print("Prints concatenated string - print(string + " 'TEST'")")
print(string + " TEST")